# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"$\n\x0ePredictRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"r\n\tDetection\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x12\n\nyolo_class\x18\x06 \x01(\x05\x12\r\n\x05label\x18\x07 \x01(\t\";\n\x0fPredictResponse\x12(\n\ndetections\x18\x01 \x03(\x0b\x32\x14.inference.Detection\"\x0f\n\rHealthRequest\"\x86\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x35\n\x06models\x18\x02 \x03(\x0b\x32%.inference.HealthResponse.ModelsEntry\x1a-\n\x0bModelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x93\x01\n\x10InferenceService\x12@\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\x12=\n\x06Health\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE_MODELSENTRY']._loaded_options = None
  _globals['_HEALTHRESPONSE_MODELSENTRY']._serialized_options = b'8\001'
  _globals['_PREDICTREQUEST']._serialized_start=30
  _globals['_PREDICTREQUEST']._serialized_end=66
  _globals['_DETECTION']._serialized_start=68
  _globals['_DETECTION']._serialized_end=182
  _globals['_PREDICTRESPONSE']._serialized_start=184
  _globals['_PREDICTRESPONSE']._serialized_end=243
  _globals['_HEALTHREQUEST']._serialized_start=245
  _globals['_HEALTHREQUEST']._serialized_end=260
  _globals['_HEALTHRESPONSE']._serialized_start=263
  _globals['_HEALTHRESPONSE']._serialized_end=397
  _globals['_HEALTHRESPONSE_MODELSENTRY']._serialized_start=352
  _globals['_HEALTHRESPONSE_MODELSENTRY']._serialized_end=397
  _globals['_INFERENCESERVICE']._serialized_start=400
  _globals['_INFERENCESERVICE']._serialized_end=547
# @@protoc_insertion_point(module_scope)
